### ISSUE TITLE
Positioning issues with vertical taskbar on Windows

### ISSUE THREAD

**Issue by EmmaStott** [jasonlong/mater#79]
I just fired up Mater on Windows and I'm having some issues with the positioning due to my use of a vertical taskbar.

If the icon is set to always show, the Mater window is obscured behind the taskbar:

![mater-bug-1](https://user-images.githubusercontent.com/1121948/68545841-da5b9900-03c8-11ea-8d37-4ca508ac2172.png)

If it's set to hide in the system tray, it's better but still partially hidden:

![mater-bug-2](https://user-images.githubusercontent.com/1121948/68545845-dfb8e380-03c8-11ea-9e8c-609c3dba5c14.png)

This looks like an upstream issue with the menubar package: https://github.com/maxogden/menubar/issues/232

P.S. Thanks for the cool app!

**Comment by jasonlong** [comment]
Hey thanks for the issue @EmmaStott. Unfortunately, I don't think there's much I can do on my end to help with this one since, as you mentioned, it seems to be something that should be fixed in `menubar`. I'll keep it open to keep tabs on though.

**Comment by jasonlong** [comment]
@EmmaStott I know this is a year old, but if you're still using Mater could you tell me if this is still a problem with the [latest version](https://github.com/jasonlong/mater/releases/tag/v1.0.7)?

**Comment by EmmaStott** [comment]
Hi @jasonlong , I just downloaded 1.0.7 and unfortunately the issue is still present.

Hopefully the issue gets fixed upstream at some point!

**Comment by jasonlong** [comment]
Well shoot, thanks for checking @EmmaStott. I'll see if I can find a way to track this down.
